version: '3.8'

services:
  web:
    image: httpd:2.4
    container_name: apache-pension-calculator
    ports:
      - "8080:80"
    volumes:
      - .:/usr/local/apache2/htdocs/
    restart: unless-stopped
